apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dev.bartho@gmail.com
    privateKeySecretRef:
      name: letsencrypt-issuer
    solvers:
      - dns01:
          cloudflare:
            email: dev.bartho@gmail.com
            apiTokenSecretRef:
              name: cert-manager-secrets
              key: CLOUDFLARE_API_TOKEN