access_control:
  default_policy: one_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.20.0.0/12", "192.168.0.0/16"]

# rules:
  # - domain: "auth.${SECRET_PUBLIC_DOMAIN}"
  #   policy: bypass

  # - domain: "*.${SECRET_PUBLIC_DOMAIN}"
  #   policy: bypass
  #   networks: ["internal"]

  # - domain:
  #     - "radarr-test.${SECRET_PUBLIC_DOMAIN}"
  #   policy: bypass
  #   resources: ["^/api([?/].*)?$"]

  # - domain: ["*.${SECRET_PUBLIC_DOMAIN}"]
  #   policy: bypass
  #   networks: ["internal"]

ntp:
  address: 'udp://pool.ntp.org:123'
  max_desync: '3s'
  disable_startup_check: true

duo_api:
  disable: true

default_redirection_url: https://start.home.bartho.dev
theme: light

log:
  level: debug

server:
  disable_healthcheck: true
  port: 8000

session:
  domain: bartho.dev

telemetry:
  metrics:
    enabled: true
    address: tcp://0.0.0.0:8080

totp:
  disable: true

webauthn:
  disable: true

storage:
  local:
    path: /data/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: '/data/notification.txt'

authentication_backend:
  ldap:
    implementation: custom
    address: ldap://lldap-ldap.lldap.svc.cluster.local:3890
    timeout: 5s
    start_tls: false
    base_dn: dc=home,dc=bartho,dc=dev
    additional_users_dn: ou=people
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_search_mode: filter
    user: uid=admin,ou=people,dc=home,dc=bartho,dc=dev
    password: password
    attributes:
      username: uid
      display_name: displayName
      group_name: cn
      mail: mail
      member_of: memberOf
  password_reset:
    disable: true
  refresh_interval: 1m

# identity_providers:
#   oidc:
#     access_token_lifespan: 1h
#     authorize_code_lifespan: 3m
#     id_token_lifespan: 1h
#     refresh_token_lifespan: 90m
#     enforce_pkce: public_clients_only
#     cors:
#       endpoints:
#         - authorization
#         - token
#         - revocation
#         - introspection
#       allowed_origins_from_client_redirect_uris: true
#     # clients:
#     # - id: grafana
#     #   description: Grafana
#     #   secret: ${SECRET_GRAFANA_OAUTH_CLIENT_SECRET}
#     #   public: false
#     #   authorization_policy: one_factor
#     #   pre_configured_consent_duration: 1y
#     #   scopes:
#     #     - openid
#     #     - profile
#     #     - groups
#     #     - email
#     #   redirect_uris:
#     #     - https://grafana.${SECRET_PUBLIC_DOMAIN}/login/generic_oauth
#     #   userinfo_signing_algorithm: none