apiVersion: v2
name: kube-prometheus-stack
version: 0.0.0
dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 73.2.0
  - name: longhorn-volume-manager
    repository: oci://registry-1.docker.io/barthodev
    version: 0.1.20
