apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: seafile-secrets
  namespace: infisical
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: seafile # Control destination namespaces
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: seafile # Control auto-reflection namespaces
spec:
  hostAPI: https://infisical.bartho.dev/api
  resyncInterval: 10
  authentication:
    serviceToken:
      secretsScope:
        envSlug: prod
        secretsPath: "/seafile"
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: infisical
  managedSecretReference:
    creationPolicy: "Owner"
    secretName: seafile-secrets
    secretNamespace: infisical