longhorn-volume-manager:
  volumes:
    - appName: authelia
      volumeName: data
      volumeSize: 1


authelia:
  defaultPodOptions:
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"

  controllers:
    main:
      replicas: 1
      containers:
        main:
          image:
            repository: docker.io/authelia/authelia
            tag: 4.39.4
          env:
            PUID: 1000
            PGID: 1000
            TZ: Europe/Paris
            # AUTHELIA_NOTIFIER_SMTP_HOST: ${SMTP_HOST}
            # AUTHELIA_NOTIFIER_SMTP_PORT: 587
            # AUTHELIA_NOTIFIER_SMTP_SENDER: "Authelia <${SMTP_EMAIL}>"
            # AUTHELIA_NOTIFIER_SMTP_USERNAME: "${SMTP_EMAIL}"
            # AUTHELIA_NOTIFIER_SMTP_PASSWORD: "${SECRET_SMTP_PASSWORD}"
            # AUTHELIA_SESSION_REDIS_HOST: authelia-redis
            # AUTHELIA_SESSION_REDIS_PORT: 6379
            # AUTHELIA_STORAGE_POSTGRES_DATABASE: authelia
            # AUTHELIA_STORAGE_POSTGRES_USERNAME: authelia
            # AUTHELIA_STORAGE_POSTGRES_HOST: homelab-pgsql.database
          envFrom:
            - secretRef:
                name: authelia-secrets
          securityContext:
            runAsUser: 0
            runAsGroup: 0

  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 8000

  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-issuer
      hosts:
        - host: &host "authelia.home.bartho.dev"
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - secretName: authelia-tls
          hosts:
            - *host

  persistence:
    data:
      existingClaim: pvc-authelia-authelia-data
      globalMounts:
        - path: /data

    config:
      enabled: true
      type: configMap
      name: authelia-configmap
      globalMounts:
        - path: /config/configuration.yml
          subPath: configuration.yml
