name: Publish Docker image

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Get latest git tag (with fallback)
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "12.0.14")
          echo "version=$TAG" >> $GITHUB_OUTPUT

      - name: Load Docker image
        run: docker load -i image.tar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag image for ghcr
        run: docker tag estiam-files:${{ steps.get_tag.outputs.version }} ghcr.io/${{ github.repository_owner }}/estiam-files:${{ steps.get_tag.outputs.version }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/estiam-files:${{ steps.get_tag.outputs.version }}

  deploy:
    runs-on: ubuntu-latest
    needs: push
    steps:

    - name: Get latest git tag (with fallback)
      id: get_tag
      run: |
        TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "12.0.14")
        echo "version=$TAG" >> $GITHUB_OUTPUT

    - name: Check if image tag needs update
      id: check_tag
      run: |
        current_tag=$(grep 'tag:' infra/kube/apps/seafile/seafile/values.yaml | head -1 | awk '{print $2}')
        if [ "$current_tag" = "${{ steps.get_tag.outputs.version }}" ]; then
          echo "skip_commit=true" >> $GITHUB_OUTPUT
        else
          echo "skip_commit=false" >> $GITHUB_OUTPUT
        fi

    - name: Update values.yaml with new image tag
      if: steps.check_tag.outputs.skip_commit == 'false'
      run: |
        awk '
          $0 ~ /repository: ghcr.io\/barthofu\/estiam-files/ {f=1; print; next}
          f && $0 ~ /tag:/ {sub(/tag: .*/, "tag: '"${{ steps.get_tag.outputs.version }}"'"); f=0}
          {print}
        ' infra/kube/apps/seafile/seafile/values.yaml > tmp && mv tmp infra/kube/apps/seafile/seafile/values.yaml

    - name: Commit and push updated values.yaml
      if: steps.check_tag.outputs.skip_commit == 'false'
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add infra/kube/apps/seafile/seafile/values.yaml
        git commit -m "chore: update estiam-files image tag to ${{ steps.get_tag.outputs.version }} [skip ci]" || echo "No changes to commit"
        git push
